version: '3'

services:

  api:
    container_name: ear-api
    build:
      context: .
    environment:
      NODE_ENV: production
      EAR_API_PORT: $EAR_API_PORT
      EAR_DB_HOST: $EAR_DB_HOST
      EAR_DB_PORT: $EAR_DB_PORT
      EAR_DB_NAME: $EAR_DB_NAME
      EAR_DB_USER: $EAR_DB_USER
      EAR_DB_PASSWORD: $EAR_DB_PASSWORD
    ports:
      - "$EAR_API_PORT:$EAR_API_PORT"
    networks:
      - express_api_ref

networks:
  express_api_ref:
    name: express_api_ref