version: '3'

services:

  devcontainer:
    container_name: ear-devcontainer
    init: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      - ..:/workspace:cached # VSCode workspace
      - ~/.aws:/home/node/.aws:cached # AWS credentials
      - /var/run/docker.sock:/var/run/docker-host.sock # host's Docker daemon
    networks:
      - express_api_ref

networks:
  express_api_ref:
    name: express_api_ref