version: '3'

services:

  db:
    container_name: express-api-ref-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - $EAR_DB_PORT:$EAR_DB_PORT
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=$EAR_DB_NAME
      - MYSQL_USER=$EAR_DB_USER
      - MYSQL_PASSWORD=$EAR_DB_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql

  db-migrate:
    container_name: express-api-ref-db-migrate
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-storage: