version: '3'

services:

  db:
    container_name: ref-cdk-express-api-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql

  db-migrate:
    container_name: ref-cdk-express-api-db-migrate
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-storage: